import * as fs from 'node:fs'
import * as path from 'node:path'
import type {
  ErrorMapping,
  Field,
  Method,
  Model,
  Space,
  Table,
  UseCase,
  Validation,
} from '@pizza-doc/core'
import type { ParsedArgs } from '../util/args.js'
import { bold, cyan, dim, green, red } from '../util/colors.js'
import { loadSpaceForCli } from '../util/load.js'
import { resolveSpaceDir } from '../util/space-path.js'
import { allComponents, allModels, allTables } from '../util/space-walk.js'

/**
 * `pd export <format> [flags]`
 *
 * Sub-commands:
 *   - `openapi` — OpenAPI 3.1 JSON/YAML from controllers + DTOs.
 *   - `implementation-brief <usecase-id>` — self-contained markdown for
 *     an LLM implementer.
 *
 * Both reads only. Output defaults to stdout; `--out <file>` writes to
 * disk.
 */
export async function cmdExport(args: ParsedArgs): Promise<number> {
  const sub = args.positional[0]
  const rest: ParsedArgs = { ...args, positional: args.positional.slice(1) }
  switch (sub) {
    case 'openapi':
      return await exportOpenApi(rest)
    case 'implementation-brief':
      return await exportImplementationBrief(rest)
    case 'typescript-types':
    case 'ts-types':
      return await exportTypeScriptTypes(rest)
    case 'go-types':
      return await exportGoTypes(rest)
    case 'go-interfaces':
      return await exportGoInterfaces(rest)
    case 'operations':
      return await exportOperations(rest)
    default:
      console.error(
        red(
          'usage: pd export <openapi | implementation-brief <usecase-id> | typescript-types | go-types | go-interfaces> [spaces/<id>]',
        ),
      )
      return 2
  }
}

// ---------- shared codegen helpers ----------

interface CodegenOptions {
  /** Output file; if omitted, writes to stdout. */
  out?: string
}

function readCodegenOptions(args: ParsedArgs): CodegenOptions {
  const opts: CodegenOptions = {}
  if (typeof args.flags.out === 'string') opts.out = args.flags.out
  return opts
}

function emit(content: string, opts: CodegenOptions): number {
  if (opts.out) {
    fs.mkdirSync(path.dirname(opts.out), { recursive: true })
    fs.writeFileSync(opts.out, content)
    console.log(`${green('✓')} wrote ${path.relative(process.cwd(), opts.out)}`)
  } else {
    process.stdout.write(content.endsWith('\n') ? content : `${content}\n`)
  }
  return 0
}

function generatedBanner(format: string, space: Space, language: 'ts' | 'go'): string {
  // Go convention: the line must match /^\/\/ Code generated .* DO NOT EDIT\.$/
  // for `go vet` and IDE tooling to skip it. TypeScript has no equivalent
  // contract; we use the same wording for consistency.
  const _ = language
  return [
    '// Code generated by pizza-doc. DO NOT EDIT.',
    `// Regenerate with: pd export ${format}`,
    `// Source: space ${space.meta.id}@${space.meta.version}`,
    '',
  ].join('\n')
}

// ---------- openapi ----------

async function exportOpenApi(args: ParsedArgs): Promise<number> {
  const { space } = await loadSpaceForCli(resolveSpaceDir(args.positional[0]))
  const doc = buildOpenApi(space)
  const out = typeof args.flags.out === 'string' ? args.flags.out : undefined
  const json = JSON.stringify(doc, null, 2)
  if (out) {
    fs.mkdirSync(path.dirname(out), { recursive: true })
    fs.writeFileSync(out, json)
    console.log(`${green('✓')} wrote ${path.relative(process.cwd(), out)}`)
  } else {
    process.stdout.write(`${json}\n`)
  }
  return 0
}

interface OpenApiDoc {
  openapi: '3.1.0'
  info: { title: string; version: string; description?: string }
  paths: Record<string, Record<string, OpenApiOperation>>
  components: { schemas: Record<string, OpenApiSchema> }
}
interface OpenApiOperation {
  operationId: string
  summary?: string
  tags?: string[]
  parameters?: Array<{
    name: string
    in: 'path' | 'query'
    required: boolean
    schema: OpenApiSchema
  }>
  requestBody?: { required: boolean; content: { 'application/json': { schema: OpenApiSchema } } }
  responses: Record<
    string,
    { description: string; content?: { 'application/json': { schema: OpenApiSchema } } }
  >
}
interface OpenApiSchema {
  $ref?: string
  type?: 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object'
  format?: string
  minLength?: number
  maxLength?: number
  minimum?: number
  maximum?: number
  pattern?: string
  enum?: string[]
  items?: OpenApiSchema
  properties?: Record<string, OpenApiSchema>
  required?: string[]
  nullable?: boolean
  description?: string
}

function buildOpenApi(space: Space): OpenApiDoc {
  const info: OpenApiDoc['info'] = {
    title: space.meta.name,
    version: space.meta.version,
  }
  if (space.meta.description) info.description = space.meta.description
  const doc: OpenApiDoc = {
    openapi: '3.1.0',
    info,
    paths: {},
    components: { schemas: {} },
  }

  // Schemas: one per model across the space.
  const modelByName = new Map<string, Model>()
  for (const { model } of allModels(space)) {
    modelByName.set(model.name, model)
    doc.components.schemas[model.name] = modelToSchema(model)
  }

  // Paths: one per controller method with httpMethod + httpPath.
  for (const { component, module } of allComponents(space)) {
    if (component.type !== 'controller') continue
    const errorMapping = module.errorMapping ?? []
    for (const m of component.methods) {
      if (!m.httpMethod || !m.httpPath) continue
      const pathKey = m.httpPath
      const op = methodToOperation(component.id, m, modelByName, errorMapping)
      doc.paths[pathKey] ??= {}
      const pathItem = doc.paths[pathKey]
      if (!pathItem) continue
      pathItem[m.httpMethod.toLowerCase()] = op
    }
  }

  return doc
}

function methodToOperation(
  componentId: string,
  method: Method,
  modelByName: Map<string, Model>,
  errorMapping: ErrorMapping[],
): OpenApiOperation {
  const op: OpenApiOperation = {
    operationId: `${componentId}_${method.name}`,
    tags: [componentId],
    responses: {
      '200': {
        description: 'OK',
        ...(method.returns && method.returns !== 'void'
          ? {
              content: {
                'application/json': { schema: typeToSchema(method.returns, modelByName) },
              },
            }
          : {}),
      },
    },
  }
  if (method.description) op.summary = method.description

  // Path/query params vs body.
  const pathTokens = new Set(
    (method.httpPath?.match(/\{(\w+)\}/g) ?? []).map((s) => s.slice(1, -1)),
  )
  for (const p of method.params) {
    const resolved = modelByName.get(stripWrappers(p.type))
    if (resolved) {
      // Body.
      op.requestBody = {
        required: !p.optional,
        content: {
          'application/json': {
            schema: typeToSchema(p.type, modelByName),
          },
        },
      }
    } else if (pathTokens.has(p.name)) {
      op.parameters ??= []
      op.parameters.push({
        name: p.name,
        in: 'path',
        required: true,
        schema: typeToSchema(p.type, modelByName),
      })
    } else {
      op.parameters ??= []
      op.parameters.push({
        name: p.name,
        in: 'query',
        required: !p.optional,
        schema: typeToSchema(p.type, modelByName),
      })
    }
  }

  // Error responses from module-level errorMapping.
  for (const em of errorMapping) {
    op.responses[String(em.httpStatus)] ??= {
      description: em.description ?? em.code ?? em.exception,
    }
  }

  return op
}

function modelToSchema(model: Model): OpenApiSchema {
  const properties: Record<string, OpenApiSchema> = {}
  const required: string[] = []
  for (const f of model.fields) {
    properties[f.name] = fieldToSchema(f)
    if (!f.optional) required.push(f.name)
  }
  const out: OpenApiSchema = {
    type: 'object',
    properties,
  }
  if (model.description) out.description = model.description
  if (required.length > 0) out.required = required
  return out
}

function fieldToSchema(field: Field): OpenApiSchema {
  const inner = typeToSchemaBare(field.type)
  if (field.validation) {
    applyValidation(inner, field.validation)
  }
  // `cardinality: many` wraps the scalar/$ref in an OpenAPI `array` —
  // unless the author already encoded the array in `type` (`List<X>`,
  // `X[]`), in which case `typeToSchemaBare` would not have produced an
  // array shape anyway because it strips collection wrappers. Keep the
  // wrap one-level only to mirror the TS/Go emitters.
  if (field.cardinality === 'many' && inner.type !== 'array') {
    const out: OpenApiSchema = { type: 'array', items: inner }
    if (field.description) out.description = field.description
    return out
  }
  if (field.description) inner.description = field.description
  return inner
}

function applyValidation(schema: OpenApiSchema, v: Validation): void {
  if (v.format) schema.format = v.format
  if (v.minLength !== undefined) schema.minLength = v.minLength
  if (v.maxLength !== undefined) schema.maxLength = v.maxLength
  if (v.min !== undefined) schema.minimum = v.min
  if (v.max !== undefined) schema.maximum = v.max
  if (v.pattern !== undefined) schema.pattern = v.pattern
  if (v.enumValues) schema.enum = [...v.enumValues]
}

function stripWrappers(t: string): string {
  let s = t.trim()
  s = s.replace(/\?$/, '')
  s = s.replace(/\[\]$/, '')
  const wrap = s.match(/^(List|Array|Set|Optional)<(.+)>$/i)
  if (wrap?.[2]) return stripWrappers(wrap[2])
  const paren = s.match(/^([a-z_]+)\s*\(/i)
  if (paren?.[1]) return paren[1]
  return s
}

function typeToSchema(type: string, modelByName: Map<string, Model>): OpenApiSchema {
  const trimmed = type.trim()
  // Optional / nullable.
  if (trimmed.endsWith('?')) {
    const inner = typeToSchema(trimmed.slice(0, -1).trim(), modelByName)
    return { ...inner, nullable: true }
  }
  // List wrappers. `Collection<X>` is treated as `List<X>` — both are
  // unordered iterables on the wire.
  if (trimmed.endsWith('[]')) {
    return { type: 'array', items: typeToSchema(trimmed.slice(0, -2).trim(), modelByName) }
  }
  const wrap = trimmed.match(/^(List|Array|Set|Collection)<(.+)>$/i)
  if (wrap?.[2]) {
    return { type: 'array', items: typeToSchema(wrap[2].trim(), modelByName) }
  }
  const opt = trimmed.match(/^Optional<(.+)>$/i)
  if (opt?.[1]) {
    const inner = typeToSchema(opt[1].trim(), modelByName)
    return { ...inner, nullable: true }
  }
  // `Page<X>` — Spring Data pagination envelope. Translated to the
  // canonical 5-field envelope used by every Spring-Data-backed admin
  // API (content + totalElements + totalPages + number + size). The
  // generated `Page` schema is stable across `X` and lives in the
  // shared `components.schemas` block so every Page<X> $refs into the
  // same inline shape.
  const page = trimmed.match(/^Page<(.+)>$/)
  if (page?.[1]) {
    const innerType = page[1].trim()
    const itemSchema = modelByName.has(innerType)
      ? { $ref: `#/components/schemas/${innerType}` }
      : typeToSchema(innerType, modelByName)
    return {
      type: 'object',
      properties: {
        content: { type: 'array', items: itemSchema },
        totalElements: { type: 'integer' },
        totalPages: { type: 'integer' },
        number: { type: 'integer' },
        size: { type: 'integer' },
      },
      required: ['content', 'totalElements', 'totalPages', 'number', 'size'],
    }
  }
  // `Pageable` — Spring Data request envelope (page + size + sort). The
  // wire form is the query-string trio `?page=&size=&sort=`; we expose
  // it as an inline object so OpenAPI clients can model it as a body
  // when needed. Most controller methods will not see it as a body
  // (Spring binds it from query params) but `pd export openapi`
  // serializes it for completeness.
  if (trimmed === 'Pageable') {
    return {
      type: 'object',
      properties: {
        page: { type: 'integer' },
        size: { type: 'integer' },
        sort: { type: 'array', items: { type: 'string' } },
      },
    }
  }
  // `Specification<X>` — Spring Data JPA criteria builder. There is no
  // meaningful wire shape (it is purely an in-process query AST); we
  // emit an opaque object so OpenAPI does not lie about a structure.
  if (/^Specification<.+>$/.test(trimmed)) {
    return { type: 'object', description: 'Opaque query specification (Spring Data Specification)' }
  }
  // Model reference.
  if (modelByName.has(trimmed)) {
    return { $ref: `#/components/schemas/${trimmed}` }
  }
  return typeToSchemaBare(trimmed)
}

function typeToSchemaBare(type: string): OpenApiSchema {
  const base = type
    .trim()
    .toLowerCase()
    .replace(/\(.*\)$/, '') // strip decimal(19,4)
  switch (base) {
    case 'string':
    case 'text':
      return { type: 'string' }
    case 'uuid':
      return { type: 'string', format: 'uuid' }
    case 'url':
    case 'uri':
      return { type: 'string', format: 'uri' }
    case 'int':
    case 'integer':
    case 'long':
    case 'smallint':
    case 'bigint':
      return { type: 'integer' }
    case 'number':
    case 'float':
    case 'double':
    case 'decimal':
    case 'numeric':
      return { type: 'number' }
    case 'boolean':
    case 'bool':
      return { type: 'boolean' }
    case 'timestamp':
    case 'timestamptz':
    case 'datetime':
    // `instant` is the Java/JSR-310 `java.time.Instant` — a moment on the
    // UTC timeline serialized to ISO-8601 over JSON. Same wire-shape as
    // `timestamp`, kept as a separate case so spec authors who think in
    // Java types do not have to translate.
    case 'instant':
      return { type: 'string', format: 'date-time' }
    case 'date':
      return { type: 'string', format: 'date' }
    default:
      return { type: 'string', description: `Unmapped type: ${type}` }
  }
}

// ---------- implementation-brief ----------

async function exportImplementationBrief(args: ParsedArgs): Promise<number> {
  const ucid = args.positional[0]
  if (!ucid) {
    console.error(red('usage: pd export implementation-brief <usecase-id> [spaces/<id>]'))
    return 2
  }
  const { space } = await loadSpaceForCli(resolveSpaceDir(args.positional[1]))
  const uc = space.useCases.find((u) => u.id === ucid)
  if (!uc) {
    console.error(red(`use case not found: ${ucid}`))
    return 1
  }
  const brief = renderBrief(space, uc)
  const out = typeof args.flags.out === 'string' ? args.flags.out : undefined
  if (out) {
    fs.mkdirSync(path.dirname(out), { recursive: true })
    fs.writeFileSync(out, brief)
    console.log(`${green('✓')} wrote ${path.relative(process.cwd(), out)}`)
  } else {
    process.stdout.write(brief)
  }
  return 0
}

function renderBrief(space: Space, uc: UseCase): string {
  const lines: string[] = []
  const push = (...xs: string[]) => lines.push(...xs)

  // ----- Header -----
  push(`# Implementation brief: ${uc.name}`, '')
  push(`> Use case id: \`${uc.id}\``)
  push(`> Actor: \`${uc.actor}\``)
  push(`> Trigger: ${uc.trigger}`)
  if (space.meta.implementationLanguage) {
    push(
      `> Target stack: ${space.meta.implementationLanguage}${space.meta.implementationFramework ? `/${space.meta.implementationFramework}` : ''}`,
    )
  }
  push('')
  if (uc.description) push(uc.description, '')

  // ----- Requires -----
  if (uc.requires.length > 0) {
    push('## Requirements (guards)', '')
    for (const r of uc.requires) {
      const bits: string[] = []
      if (r.role) bits.push(`global role = ${r.role}`)
      if (r.tenantRole) bits.push(`tenant role = ${r.tenantRole}`)
      if (r.tenantContext !== undefined) bits.push(`tenantContext = ${r.tenantContext}`)
      if (r.flag) bits.push(`feature flag = ${r.flag}`)
      push(`- ${bits.join(', ')}${r.description ? ` — ${r.description}` : ''}`)
    }
    push('')
  }

  // ----- Steps -----
  push('## Happy path', '')
  for (const [i, s] of uc.steps.entries()) {
    const via = s.via ? ` via \`${s.via}\`` : ''
    const proto = s.protocol ? ` [${s.protocol}]` : ''
    push(`${i + 1}. \`${s.from}\` → \`${s.to}\`${via}${proto}`)
    if (s.description) push(`   ${s.description}`)
  }
  push('')

  // ----- Error flows -----
  if (uc.errorFlows.length > 0) {
    push('## Error flows', '')
    for (const ef of uc.errorFlows) {
      push(`### ${ef.id}`, '', `**Condition:** ${ef.condition}`, '')
      for (const [i, s] of ef.steps.entries()) {
        push(`${i + 1}. \`${s.from}\` → \`${s.to}\`${s.description ? ` — ${s.description}` : ''}`)
      }
      if (ef.resultDescription) push('', `**Result:** ${ef.resultDescription}`)
      push('')
    }
  }

  // ----- Invariants -----
  if (uc.invariants.pre.length > 0 || uc.invariants.post.length > 0) {
    push('## Invariants', '')
    if (uc.invariants.pre.length > 0) {
      push('**Pre:**')
      for (const x of uc.invariants.pre) push(`- ${x}`)
      push('')
    }
    if (uc.invariants.post.length > 0) {
      push('**Post:**')
      for (const x of uc.invariants.post) push(`- ${x}`)
      push('')
    }
  }

  // ----- Data flow -----
  if (uc.dataFlow.length > 0) {
    push('## Data flow (field → column / DTO)', '')
    for (const df of uc.dataFlow) {
      const arrow = df.cardinality === 'many' ? '⇉' : '→'
      push(
        `- \`${df.sourceField}\` ${arrow} \`${df.targetField}\`${df.transform ? ` — ${df.transform}` : ''}`,
      )
    }
    push('')
  }

  // ----- Referenced entities (flattened) -----
  const refs = collectReferencedEntities(space, uc)
  if (refs.models.length > 0) {
    push('## Models referenced', '')
    for (const m of refs.models) push(renderModelBlock(m))
  }
  if (refs.tables.length > 0) {
    push('## Tables referenced', '')
    for (const t of refs.tables) push(renderTableBlock(t))
  }
  if (refs.errorMapping.length > 0) {
    push('## Exception → HTTP status mapping', '')
    push('| exception | status | code |')
    push('|---|---|---|')
    for (const em of refs.errorMapping) {
      push(`| ${em.exception} | ${em.httpStatus} | ${em.code ?? ''} |`)
    }
    push('')
  }

  push('---')
  push(
    '',
    `Generated by \`pd export implementation-brief ${uc.id}\`. This brief is self-contained — everything the implementer needs to write correct-first-time code for this use case lives in this file.`,
  )

  return lines.join('\n')
}

interface ReferencedBlock {
  models: Model[]
  tables: Table[]
  errorMapping: ErrorMapping[]
}

function collectReferencedEntities(space: Space, uc: UseCase): ReferencedBlock {
  const modelIds = new Set<string>()
  const tableIds = new Set<string>()
  const moduleIds = new Set<string>()

  const eat = (ref: string | undefined): void => {
    if (!ref) return
    const modMatch = ref.match(/^module:([^/]+)/)
    if (modMatch?.[1]) moduleIds.add(modMatch[1])
    const modelMatch = ref.match(/\/model:([^/]+)/)
    if (modelMatch?.[1]) modelIds.add(modelMatch[1])
    const tableMatch = ref.match(/\/table:([^/]+)/)
    if (tableMatch?.[1]) tableIds.add(tableMatch[1])
  }

  for (const step of uc.steps) {
    eat(step.from)
    eat(step.to)
    eat(step.via)
  }
  for (const ef of uc.errorFlows)
    for (const s of ef.steps) {
      eat(s.from)
      eat(s.to)
      eat(s.via)
    }
  for (const df of uc.dataFlow) {
    const src = df.sourceField.split('.')[0]
    const tgt = df.targetField.split('.')[0]
    if (src) modelIds.add(src) // may be a model or a table — we check both
    if (tgt) {
      modelIds.add(tgt)
      tableIds.add(tgt)
    }
  }

  const models: Model[] = []
  for (const { model } of allModels(space)) {
    if (modelIds.has(model.id) || modelIds.has(model.name)) models.push(model)
  }
  const tables: Table[] = []
  for (const { table } of allTables(space)) {
    if (tableIds.has(table.id) || tableIds.has(table.name)) tables.push(table)
  }
  const errorMapping: ErrorMapping[] = []
  for (const mod of space.modules) {
    if (!moduleIds.has(mod.id)) continue
    for (const em of mod.errorMapping ?? []) errorMapping.push(em)
  }

  return { models, tables, errorMapping }
}

function renderModelBlock(m: Model): string {
  const lines: string[] = []
  lines.push(`### ${m.name} (${m.modelKind})`)
  if (m.description) lines.push('', m.description)
  if (m.persistedAs) lines.push('', `_Persisted as:_ \`${m.persistedAs}\``)
  lines.push('')
  lines.push('| field | type | optional | validation |')
  lines.push('|---|---|---|---|')
  for (const f of m.fields) {
    const v = f.validation ? formatValidation(f.validation) : ''
    lines.push(`| ${f.name} | ${f.type} | ${f.optional ? 'yes' : ''} | ${v} |`)
  }
  if (m.stateMachine) {
    lines.push('', `**State machine on field \`${m.stateMachine.field}\`:**`)
    lines.push(`- states: ${m.stateMachine.states.join(', ')}`)
    if (m.stateMachine.initial) lines.push(`- initial: ${m.stateMachine.initial}`)
    if (m.stateMachine.terminal.length > 0)
      lines.push(`- terminal: ${m.stateMachine.terminal.join(', ')}`)
    lines.push('- transitions:')
    for (const t of m.stateMachine.transitions) {
      const tos = Array.isArray(t.to) ? t.to.join(' | ') : t.to
      lines.push(
        `  - ${t.from} → ${tos}${t.on ? ` on \`${t.on}\`` : ''}${t.guard ? ` guard: ${t.guard}` : ''}`,
      )
    }
  }
  if (m.topic) lines.push('', `**Topic:** \`${m.topic}\``)
  lines.push('')
  return lines.join('\n')
}

function renderTableBlock(t: Table): string {
  const lines: string[] = []
  lines.push(`### ${t.name}`)
  if (t.description) lines.push('', t.description, '')
  lines.push('| column | sql type | null | default | pk | fk |')
  lines.push('|---|---|---|---|---|---|')
  for (const c of t.columns) {
    lines.push(
      `| ${c.name} | ${c.sqlType} | ${c.nullable ? 'yes' : ''} | ${c.default ?? ''} | ${c.primaryKey ? 'yes' : ''} | ${c.foreignKey ? `${c.foreignKey.table}.${c.foreignKey.column}` : ''} |`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

function formatValidation(v: Validation): string {
  const bits: string[] = []
  if (v.format) bits.push(`format=${v.format}`)
  if (v.minLength !== undefined) bits.push(`minLen=${v.minLength}`)
  if (v.maxLength !== undefined) bits.push(`maxLen=${v.maxLength}`)
  if (v.min !== undefined) bits.push(`min=${v.min}`)
  if (v.max !== undefined) bits.push(`max=${v.max}`)
  if (v.pattern) bits.push(`pattern=${v.pattern}`)
  if (v.enumValues) bits.push(`enum=${v.enumValues.join('\\|')}`)
  return bits.join(', ')
}

// ==========================================================================
// TypeScript types
// ==========================================================================

/**
 * `pd export typescript-types [--out file] [spaces/<id>]`
 *
 * Emits one TypeScript module that contains:
 *   - `export interface Foo { ... }` for every dto / entity / value-object / event
 *   - `export type RuntimeId = 'a' | 'b'` for every enum
 *
 * Field types are mapped from the spec's loose type strings to TS:
 *   string / text / uuid → string
 *   int / bigint / smallint / long / number / decimal / float → number
 *   boolean / bool → boolean
 *   timestamp / datetime / date → string (ISO 8601)
 *   List<X> / Array<X> / X[] → X[]
 *   Optional<X> → X | null   (and the field is also marked `?:`)
 *   Map<K, V> → Record<K, V>
 *   anything else → passed through verbatim (assumes another model name)
 */
export async function exportTypeScriptTypes(args: ParsedArgs): Promise<number> {
  const { space } = await loadSpaceForCli(resolveSpaceDir(args.positional[0]))
  const content = renderTypeScriptTypes(space)
  return emit(content, readCodegenOptions(args))
}

export function renderTypeScriptTypes(space: Space): string {
  const lines: string[] = []
  lines.push(generatedBanner('typescript-types', space, 'ts'))
  // Ordering: types before enums? doesn't matter to TypeScript — declaration
  // order is irrelevant inside a module. Group by kind for readability.
  const enums: Model[] = []
  const records: Model[] = []
  for (const { model } of allModels(space)) {
    if (model.modelKind === 'enum') enums.push(model)
    else records.push(model)
  }
  if (enums.length > 0) {
    lines.push('// ---- enums ----')
    lines.push('')
    for (const e of enums) {
      lines.push(...renderTsEnum(e))
      lines.push('')
    }
  }
  if (records.length > 0) {
    lines.push('// ---- types ----')
    lines.push('')
    for (const m of records) {
      lines.push(...renderTsRecord(m))
      lines.push('')
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderTsEnum(model: Model): string[] {
  const lines: string[] = []
  pushDocTs(lines, model.description)
  const values = model.values ?? []
  if (values.length === 0) {
    lines.push(`export type ${model.name} = never  // empty enum`)
    return lines
  }
  const union = values.map((v) => JSON.stringify(v)).join(' | ')
  lines.push(`export type ${model.name} = ${union}`)
  // Const tuple makes `Object.values`-style iteration trivial in
  // generated code without resorting to runtime metadata.
  lines.push(
    `export const ${model.name}Values = [${values.map((v) => JSON.stringify(v)).join(', ')}] as const`,
  )
  return lines
}

function renderTsRecord(model: Model): string[] {
  const lines: string[] = []
  pushDocTs(lines, model.description)
  lines.push(`export interface ${model.name} {`)
  for (const f of model.fields) {
    if (f.description) lines.push(`  /** ${escapeJsDoc(f.description)} */`)
    lines.push(`  ${f.name}${f.optional ? '?' : ''}: ${tsFieldType(f)}`)
  }
  lines.push('}')
  return lines
}

/**
 * Map a `Field` to its TypeScript surface type. Honors `cardinality: many`
 * by wrapping the mapped type in `T[]` unless the author already encoded
 * the collection in `type` (`List<X>`, `X[]`) — we never double-wrap.
 */
function tsFieldType(f: Field): string {
  const base = mapTsType(f.type)
  if (f.cardinality === 'many' && !isTsCollection(base)) return `${base}[]`
  return base
}

function isTsCollection(t: string): boolean {
  // `T[]`, `T[][]`, `Foo<bar>[]`. The trailing `]` is the cheap structural
  // check that covers everything `mapTsType` emits for collections.
  return t.trimEnd().endsWith(']')
}

function pushDocTs(lines: string[], description?: string): void {
  if (!description) return
  const trimmed = description.trim()
  if (!trimmed) return
  if (!trimmed.includes('\n')) {
    lines.push(`/** ${escapeJsDoc(trimmed)} */`)
    return
  }
  lines.push('/**')
  for (const ln of trimmed.split('\n')) lines.push(` * ${escapeJsDoc(ln)}`)
  lines.push(' */')
}

function escapeJsDoc(s: string): string {
  return s.replace(/\*\//g, '*\\/')
}

function mapTsType(raw: string): string {
  const t = raw.trim()
  if (!t) return 'unknown'
  // `X?` suffix — Kotlin/Swift-style nullable. Behaves the same as
  // `Optional<X>`: the field-level `?:` covers "key may be missing", the
  // `| null` covers "value may be null".
  if (t.endsWith('?') && !t.endsWith('[]?')) {
    const inner = t.slice(0, -1).trim()
    if (inner) return `${mapTsType(inner)} | null`
  }
  // Optional<X> → X | null. The field-level `?:` already covers
  // "key may be missing"; the `| null` covers "value may be null".
  const opt = t.match(/^Optional<(.+)>$/i) ?? t.match(/^Maybe<(.+)>$/i)
  if (opt?.[1]) return `${mapTsType(opt[1])} | null`
  // Stream<X> — push channel / lazy producer. Idiomatic TS is async iter.
  const stream = t.match(/^Stream<(.+)>$/i)
  if (stream?.[1]) return `AsyncIterable<${mapTsType(stream[1])}>`
  // List<X>, Array<X>, Set<X>, Collection<X> → X[]. Collection is treated
  // as an unordered iterable (Java/Spring spec authors use Collection<>
  // when ordering is not part of the contract).
  const list = t.match(/^(?:List|Array|Set|Collection)<(.+)>$/i)
  if (list?.[1]) return `${mapTsType(list[1])}[]`
  // X[]
  if (t.endsWith('[]')) return `${mapTsType(t.slice(0, -2))}[]`
  // Map<K, V> → Record<K, V>
  const map = t.match(/^Map<\s*([^,>]+)\s*,\s*(.+)\s*>$/i)
  if (map?.[1] && map[2]) return `Record<${mapTsType(map[1])}, ${mapTsType(map[2])}>`
  // `Page<X>` — Spring Data pagination envelope. Inline structural type
  // keeps the FE binding free of any pizza-doc runtime — every callsite
  // sees the same shape.
  const page = t.match(/^Page<(.+)>$/)
  if (page?.[1]) {
    const inner = mapTsType(page[1])
    return `{ content: ${inner}[]; totalElements: number; totalPages: number; number: number; size: number }`
  }
  // `Pageable` — Spring Data request envelope. Equivalent to the
  // query-string trio `?page=&size=&sort=`; expressed as a structural
  // object so TS code can construct it directly.
  if (t === 'Pageable') {
    return '{ page?: number; size?: number; sort?: string[] }'
  }
  // `Specification<X>` — Spring Data JPA criteria builder. Opaque to
  // non-JVM consumers; emit `unknown` so the type-check fails loudly
  // when someone accidentally constructs one outside JVM code.
  if (/^Specification<.+>$/.test(t)) return 'unknown'
  // Strip parameterised numeric sizes — varchar(255) → varchar, decimal(19,4) → decimal.
  const paren = t.match(/^([A-Za-z_]+)\s*\(/)
  const head = paren?.[1] ?? t
  const lower = head.toLowerCase()
  if (lower === 'string' || lower === 'text' || lower === 'varchar') return 'string'
  if (lower === 'uuid') return 'string'
  // `url` / `uri` — string-shaped types kept as recognised aliases so
  // generated TS does not pass them through as opaque names.
  if (lower === 'url' || lower === 'uri') return 'string'
  if (
    lower === 'int' ||
    lower === 'integer' ||
    lower === 'smallint' ||
    lower === 'long' ||
    lower === 'bigint' ||
    lower === 'number' ||
    lower === 'decimal' ||
    lower === 'numeric' ||
    lower === 'float' ||
    lower === 'double'
  )
    return 'number'
  if (lower === 'boolean' || lower === 'bool') return 'boolean'
  if (
    lower === 'timestamp' ||
    lower === 'timestamptz' ||
    lower === 'datetime' ||
    lower === 'date' ||
    // `instant` (Java `java.time.Instant`) — same ISO-8601 wire form
    // as `timestamp`, kept as a separate case so spec authors who
    // think in Java types do not have to translate.
    lower === 'instant' ||
    // `duration` — wire form is an ISO-8601 duration string. No
    // first-class TS type, so we use the string and let consumers
    // parse if needed.
    lower === 'duration'
  )
    return 'string'
  // `context` is a Go-only construct (request lifecycle / cancellation).
  // In TS we treat it as opaque so generated code does not lie about
  // the surface; consumers needing cancellation should plumb it via
  // their fetch / abort-controller signature directly.
  if (lower === 'context') return 'unknown'
  if (lower === 'json' || lower === 'jsonb') return 'unknown'
  if (lower === 'object') return 'object'
  if (lower === 'any') return 'unknown'
  if (lower === 'void') return 'void'
  if (lower === 'bytes' || lower === 'bytea' || lower === 'blob') return 'Uint8Array'
  // Pass through — assume the author named another model.
  return t
}

// ==========================================================================
// Go types
// ==========================================================================

/**
 * `pd export go-types [--package <name>] [--out file] [spaces/<id>]`
 *
 * Emits one Go file containing:
 *   - `type Foo struct { ... }` per dto / entity / value-object / event
 *   - `type RuntimeId string` + a `const ( ... )` block per enum
 *
 * Field names are PascalCased; `json:"originalName"` tags preserve the
 * spec's wire name. Optional fields become pointer types and gain
 * `omitempty`. Generated `time.Time` triggers a `"time"` import.
 *
 * Package name defaults to a snake_case version of the space id;
 * override with `--package`.
 */
export async function exportGoTypes(args: ParsedArgs): Promise<number> {
  const { space } = await loadSpaceForCli(resolveSpaceDir(args.positional[0]))
  const pkg = readPackageOption(args, space)
  const content = renderGoTypes(space, pkg)
  return emit(content, readCodegenOptions(args))
}

export function renderGoTypes(space: Space, pkg: string): string {
  resetGoExtraTypes()
  const lines: string[] = []
  lines.push(generatedBanner('go-types', space, 'go'))
  lines.push(`package ${pkg}`)
  lines.push('')
  // Render bodies first into a buffer so we know which imports are needed.
  const bodyLines: string[] = []
  const imports = new Set<string>()
  const enums: Model[] = []
  const records: Model[] = []
  for (const { model } of allModels(space)) {
    if (model.modelKind === 'enum') enums.push(model)
    else records.push(model)
  }
  for (const e of enums) {
    bodyLines.push(...renderGoEnum(e))
    bodyLines.push('')
  }
  for (const m of records) {
    bodyLines.push(...renderGoStruct(m, imports))
    bodyLines.push('')
  }
  // Emit any Java-ism helpers (Pageable / PageOfX) the structs picked up.
  // These do not need extra imports — pure Go primitives only.
  const extras = renderExtraGoTypes()
  if (imports.size > 0) {
    if (imports.size === 1) {
      const [only] = [...imports]
      lines.push(`import ${JSON.stringify(only)}`)
    } else {
      lines.push('import (')
      for (const i of [...imports].sort()) lines.push(`\t${JSON.stringify(i)}`)
      lines.push(')')
    }
    lines.push('')
  }
  lines.push(...extras)
  lines.push(...bodyLines)
  return `${lines.join('\n').trimEnd()}\n`
}

function renderGoEnum(model: Model): string[] {
  const lines: string[] = []
  pushDocGo(lines, model.description, model.name)
  lines.push(`type ${model.name} string`)
  lines.push('')
  const values = model.values ?? []
  if (values.length === 0) {
    lines.push('// (empty enum: declare values: in the spec)')
    return lines
  }
  lines.push('const (')
  for (const v of values) {
    lines.push(`\t${model.name}${enumConstSuffix(v)} ${model.name} = ${JSON.stringify(v)}`)
  }
  lines.push(')')
  return lines
}

function enumConstSuffix(value: string): string {
  // 'claude-code' → 'ClaudeCode'. Identifiers must start with a letter; if
  // the first piece starts with a digit we prefix `V` so the const is valid Go.
  const pascal = value
    .split(/[-_\s.]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
  if (!pascal) return 'Empty'
  if (/^[0-9]/.test(pascal)) return `V${pascal}`
  return pascal
}

function renderGoStruct(model: Model, imports: Set<string>): string[] {
  const lines: string[] = []
  pushDocGo(lines, model.description, model.name)
  lines.push(`type ${model.name} struct {`)
  for (const f of model.fields) {
    if (f.description) lines.push(`\t// ${f.description.replace(/\n/g, ' ')}`)
    const baseType = mapGoType(f.type, imports)
    const collectionType =
      f.cardinality === 'many' && !baseType.startsWith('[]') ? `[]${baseType}` : baseType
    const omitempty = f.optional ? ',omitempty' : ''
    // Optional collections stay slices (nil slice marshals fine); only
    // non-collection optionals become pointer types so the omitempty tag
    // can distinguish "absent" from "zero value".
    const fieldType =
      f.optional &&
      !collectionType.startsWith('[]') &&
      !collectionType.startsWith('map[') &&
      !collectionType.startsWith('*')
        ? `*${collectionType}`
        : collectionType
    lines.push(`\t${pascalCase(f.name)} ${fieldType} \`json:"${f.name}${omitempty}"\``)
  }
  lines.push('}')
  return lines
}

function pushDocGo(lines: string[], description: string | undefined, name: string): void {
  if (!description) return
  const trimmed = description.trim()
  if (!trimmed) return
  // Go style: doc comments prefix the named identifier. We start with
  // `// <Name>` if the description doesn't already.
  const startsWithName = trimmed.toLowerCase().startsWith(name.toLowerCase())
  const lead = startsWithName
    ? trimmed
    : `${name} ${trimmed.charAt(0).toLowerCase()}${trimmed.slice(1)}`
  for (const ln of lead.split('\n')) lines.push(`// ${ln}`)
}

function pascalCase(s: string): string {
  return s
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

function mapGoType(raw: string, imports: Set<string>): string {
  const t = raw.trim()
  if (!t) return 'any'
  // `X?` suffix — Kotlin/Swift-style nullable. Same treatment as
  // `Optional<X>` (optional is handled at the field/return level via a
  // pointer, not in the base type).
  if (t.endsWith('?') && !t.endsWith('[]?')) {
    const inner = t.slice(0, -1).trim()
    if (inner) return mapGoType(inner, imports)
  }
  const opt = t.match(/^Optional<(.+)>$/i) ?? t.match(/^Maybe<(.+)>$/i)
  if (opt?.[1]) return mapGoType(opt[1], imports) // optional handled at field level via pointer
  // Stream<X> — push channel / lazy producer. Idiomatic Go is a
  // receive-only channel; the producer side returns it. Authors who want
  // an iterator (Go 1.23+ iter.Seq) can post-process — channel is the
  // safer default since it works on every Go version we care about.
  const stream = t.match(/^Stream<(.+)>$/i)
  if (stream?.[1]) return `<-chan ${mapGoType(stream[1], imports)}`
  // `Promise<X>` is a TS-only async wrapper. Go methods are inherently
  // sync (concurrency is the caller's choice), so the Promise is
  // stripped — the generated Go interface returns the underlying type
  // and the standard `error`. This means a TS author who writes a
  // Promise<X> return ends up with the same Go signature an author who
  // wrote bare X would get; the only difference is on the TS side
  // (where `mapTsType` preserves the wrapper).
  const promise = t.match(/^Promise<(.+)>$/i)
  if (promise?.[1]) return mapGoType(promise[1], imports)
  // List<X>, Array<X>, Set<X>, Collection<X> → []X. Collection is
  // treated as an unordered iterable.
  const list = t.match(/^(?:List|Array|Set|Collection)<(.+)>$/i)
  if (list?.[1]) return `[]${mapGoType(list[1], imports)}`
  if (t.endsWith('[]')) return `[]${mapGoType(t.slice(0, -2), imports)}`
  const map = t.match(/^Map<\s*([^,>]+)\s*,\s*(.+)\s*>$/i)
  if (map?.[1] && map[2]) return `map[${mapGoType(map[1], imports)}]${mapGoType(map[2], imports)}`
  // `Page<X>` — Spring Data pagination envelope. We translate to a
  // concrete `PageOf<X>` struct name and remember the inner type so the
  // emitter can declare a top-level `type PageOf<X> struct { ... }`
  // exactly once even if multiple methods return the same wrapper.
  // The caller registers `PageOf<X>` in `pageWrappers` (see
  // `renderGoTypes` / `renderGoInterfaces`).
  const page = t.match(/^Page<(.+)>$/)
  if (page?.[1]) {
    const inner = page[1].trim()
    const innerGo = mapGoType(inner, imports)
    const wrapperName = `PageOf${pascalCase(inner)}`
    pageWrappersInScope.set(wrapperName, innerGo)
    return wrapperName
  }
  // `Pageable` — Spring Data request envelope. Idiomatic Go translation
  // is a small struct with the canonical trio. Registered as a one-shot
  // sentinel so the emitter declares it at most once per file.
  if (t === 'Pageable') {
    pageableInScope.value = true
    return 'Pageable'
  }
  // `Specification<X>` — Spring Data JPA criteria. Opaque outside the
  // JVM; pass through as `any` so the interface still compiles.
  if (/^Specification<.+>$/.test(t)) return 'any'
  // Inline object literal types — `{ token: string }`, `{ a: int; b?: number }`.
  // These leak from TS-influenced specs. We emit `any` so the Go file
  // compiles; the structural shape is preserved in the spec for OpenAPI
  // / TS consumers (mapTsType passes the inline shape through verbatim
  // because TS already understands it natively).
  if (t.startsWith('{') && t.endsWith('}')) return 'any'
  const paren = t.match(/^([A-Za-z_]+)\s*\(/)
  const head = paren?.[1] ?? t
  const lower = head.toLowerCase()
  if (
    lower === 'string' ||
    lower === 'text' ||
    lower === 'varchar' ||
    lower === 'uuid' ||
    // `url` is just a string with an unenforced shape constraint. Go
    // does not natively distinguish, and forcing the spec to use
    // `string` everywhere is noise — keep `url` as a recognised alias
    // so the generated Go file compiles. (OpenAPI emitter could later
    // surface `format: uri` here; not required for compile-correctness.)
    lower === 'url' ||
    lower === 'uri'
  )
    return 'string'
  if (lower === 'int' || lower === 'integer') return 'int'
  if (lower === 'smallint') return 'int16'
  if (lower === 'long' || lower === 'bigint') return 'int64'
  if (lower === 'number' || lower === 'decimal' || lower === 'numeric') return 'float64'
  if (lower === 'float') return 'float32'
  if (lower === 'double') return 'float64'
  if (lower === 'boolean' || lower === 'bool') return 'bool'
  if (
    lower === 'timestamp' ||
    lower === 'timestamptz' ||
    lower === 'datetime' ||
    lower === 'date' ||
    // `instant` (Java `java.time.Instant`) — same `time.Time` wire form
    // as `timestamp`. Kept as a separate case so spec authors who think
    // in Java types do not have to translate.
    lower === 'instant'
  ) {
    imports.add('time')
    return 'time.Time'
  }
  // `duration` — durations are first-class in Go (`time.Duration`).
  // Authors who write `Duration` in the spec almost always mean
  // `time.Duration`, not the wire-encoded ISO 8601 string. Keep the
  // ergonomic mapping; OpenAPI emitter can later render this as
  // `{ type: 'string', format: 'duration' }` if needed.
  if (lower === 'duration') {
    imports.add('time')
    return 'time.Duration'
  }
  // `context` — Go's standard request-scoped context. Always pulled in
  // by repository/orchestrator interfaces. Mapping by name keeps the
  // spec language-neutral while still emitting idiomatic Go.
  if (lower === 'context') {
    imports.add('context')
    return 'context.Context'
  }
  // Package-qualified Go stdlib references like `http.Request` or
  // `http.ResponseWriter`. Spec authors sometimes leak them through
  // params (HTTP middleware signatures); add the corresponding import
  // and pass the literal through.
  const stdPkg = t.match(/^([a-z][a-z0-9_]*)\.([A-Z][A-Za-z0-9_]*)$/)
  if (stdPkg?.[1] && stdPkg[2]) {
    const pkg = stdPkg[1]
    // Map short stdlib names to their canonical import path. Anything
    // outside this allow-list passes through unchanged and the caller
    // must declare the import manually (or the Go file fails to compile,
    // which is the correct outcome for non-stdlib package leakage).
    const stdLibImport: Record<string, string> = {
      http: 'net/http',
      url: 'net/url',
      context: 'context',
      time: 'time',
      io: 'io',
      os: 'os',
      sql: 'database/sql',
      json: 'encoding/json',
    }
    const importPath = stdLibImport[pkg]
    if (importPath) {
      imports.add(importPath)
      return t
    }
  }
  // `json` / `jsonb` → encoding/json.RawMessage. Adding the import.
  if (lower === 'json' || lower === 'jsonb') {
    imports.add('encoding/json')
    return 'json.RawMessage'
  }
  // Loose / opaque structures.
  // - `object` (TS-style "non-null structured value") → map[string]any.
  // - `any`                                            → any.
  if (lower === 'object') return 'map[string]any'
  if (lower === 'any') return 'any'
  if (lower === 'bytes' || lower === 'bytea' || lower === 'blob') return '[]byte'
  if (lower === 'void') return ''
  return t
}

/**
 * Per-emit registries for Java-isms that need a synthesized helper type
 * in the generated Go file (`Page<X>` → `PageOfX` struct, `Pageable` →
 * one shared struct). Reset at the top of every `renderGoTypes` /
 * `renderGoInterfaces` call so concurrent renders do not leak state.
 *
 * The registries are module-private mutables instead of threaded through
 * the recursive `mapGoType` signature because the alternative — passing
 * a context object through every `mapGoType` call — would touch every
 * call-site in this file. The render entry points (the only places that
 * matter) reset them; nothing else reads them mid-emit.
 */
const pageWrappersInScope: Map<string, string> = new Map()
const pageableInScope: { value: boolean } = { value: false }

function resetGoExtraTypes(): void {
  pageWrappersInScope.clear()
  pageableInScope.value = false
}

function renderExtraGoTypes(): string[] {
  const lines: string[] = []
  if (pageableInScope.value) {
    lines.push(
      '// Pageable spring Data request envelope (page + size + sort). Generated',
      '// because spec authors used the Java-side type directly.',
      'type Pageable struct {',
      '\tPage int      `json:"page"`',
      '\tSize int      `json:"size"`',
      '\tSort []string `json:"sort,omitempty"`',
      '}',
      '',
    )
  }
  // Stable ordering by wrapper name so consecutive emits produce
  // byte-identical output for the same spec.
  const wrappers = [...pageWrappersInScope.entries()].sort((a, b) => a[0].localeCompare(b[0]))
  for (const [name, inner] of wrappers) {
    lines.push(
      `// ${name} spring Data Page<${inner}> envelope. Generated because the spec`,
      `// uses Page<${inner}> as a return type.`,
      `type ${name} struct {`,
      `\tContent       []${inner} \`json:"content"\``,
      '\tTotalElements int64    `json:"totalElements"`',
      '\tTotalPages    int      `json:"totalPages"`',
      '\tNumber        int      `json:"number"`',
      '\tSize          int      `json:"size"`',
      '}',
      '',
    )
  }
  return lines
}

// ==========================================================================
// Go interfaces (component methods)
// ==========================================================================

/**
 * `pd export go-interfaces [--package <name>] [--out file] [spaces/<id>]`
 *
 * Emits one Go file with `type <Component> interface { ... }` for every
 * component that has at least one method. The signatures use the same
 * type-mapping as `go-types`, so an emitted DTO type is referenced by
 * name. Methods that return a non-void type also return an `error` —
 * a Go convention authors will need almost always anyway, and one less
 * thing to write by hand.
 */
export async function exportGoInterfaces(args: ParsedArgs): Promise<number> {
  const { space } = await loadSpaceForCli(resolveSpaceDir(args.positional[0]))
  const pkg = readPackageOption(args, space)
  const content = renderGoInterfaces(space, pkg)
  return emit(content, readCodegenOptions(args))
}

export function renderGoInterfaces(space: Space, pkg: string): string {
  resetGoExtraTypes()
  const lines: string[] = []
  lines.push(generatedBanner('go-interfaces', space, 'go'))
  lines.push(`package ${pkg}`)
  lines.push('')
  const bodyLines: string[] = []
  const imports = new Set<string>()
  // De-dup by component name — different modules can declare a component
  // with the same id (e.g. an FE-side `PreviewController` and a BE-side
  // `PreviewController`), and Go cannot have two `type X interface`
  // declarations in the same package. The service-type filter usually
  // resolves this, but the explicit Set is a safety net.
  const seen = new Set<string>()
  for (const { component, module, ref } of allComponents(space)) {
    if (component.methods.length === 0) continue
    // Skip frontend / database / queue / external modules — the Go
    // interfaces file is a contract for *backend Go services*. Frontend
    // components live in `pd export typescript-types`; database / queue
    // modules have no executable surface here.
    if (module.type !== 'service') continue
    if (seen.has(component.name)) continue
    seen.add(component.name)
    bodyLines.push(...renderGoInterface(component, ref, imports))
    bodyLines.push('')
  }
  // Any Pageable / PageOfX helpers triggered by method signatures must
  // be declared inline in this file — `internal/contracts/interfaces.go`
  // is typically the only file in the contracts package, so the
  // declarations cannot live elsewhere without `go-types` regen.
  const extras = renderExtraGoTypes()
  if (imports.size > 0) {
    if (imports.size === 1) {
      const [only] = [...imports]
      lines.push(`import ${JSON.stringify(only)}`)
    } else {
      lines.push('import (')
      for (const i of [...imports].sort()) lines.push(`\t${JSON.stringify(i)}`)
      lines.push(')')
    }
    lines.push('')
  }
  lines.push(...extras)
  lines.push(...bodyLines)
  return `${lines.join('\n').trimEnd()}\n`
}

function renderGoInterface(
  component: import('@pizza-doc/core').Component,
  ref: string,
  imports: Set<string>,
): string[] {
  const lines: string[] = []
  pushDocGo(lines, component.description ?? `Generated from ${ref}.`, component.name)
  lines.push(`type ${component.name} interface {`)
  // Go does not support method overloading, so two methods with the same
  // name within an interface (legal in Java/Spring specs) collapse to
  // one. We keep the first occurrence and skip the rest; the dropped
  // method's signature is preserved as a comment so reviewers see the
  // overload exists. The spec author should split the overload into two
  // distinct method names if both signatures need to be callable from Go.
  const seenMethods = new Set<string>()
  for (const m of component.methods) {
    const methodKey = pascalCase(m.name)
    if (seenMethods.has(methodKey)) {
      lines.push(
        `\t// SKIPPED OVERLOAD: ${m.name} — Go interfaces cannot have two methods with the same name.`,
      )
      lines.push(`\t// ${renderGoMethodSignature(m, imports)}`)
      continue
    }
    seenMethods.add(methodKey)
    if (m.description) lines.push(`\t// ${m.description.replace(/\n/g, ' ')}`)
    lines.push(`\t${renderGoMethodSignature(m, imports)}`)
  }
  lines.push('}')
  return lines
}

function renderGoMethodSignature(m: Method, imports: Set<string>): string {
  const params = m.params
    .map((p) => {
      const goType = mapGoType(p.type, imports)
      const isPtr = p.optional && !goType.startsWith('[]') && !goType.startsWith('map[')
      return `${camelCase(p.name)} ${isPtr ? `*${goType}` : goType}`
    })
    .join(', ')
  // A trailing `?` on the return type (`WsOutgoingMessage?`) marks the
  // return as nullable. Idiomatic Go for "may be absent" is a pointer
  // type; `mapGoType` strips the `?` itself, so we detect it here and
  // wrap the result. Slice / map / `any` returns stay as-is because their
  // zero value already encodes "absent".
  const returnsTrimmed = m.returns.trim()
  const returnNullable = returnsTrimmed.endsWith('?') && !returnsTrimmed.endsWith('[]?')
  let ret = mapGoType(m.returns, imports)
  if (returnNullable && ret && !ret.startsWith('[]') && !ret.startsWith('map[') && ret !== 'any') {
    ret = `*${ret}`
  }
  // `void` → just an error. Anything else → (Type, error). This keeps the
  // generated interface usable in idiomatic Go without breaking when the
  // spec stays language-neutral.
  const returnSig = ret === '' ? 'error' : `(${ret}, error)`
  return `${pascalCase(m.name)}(${params}) ${returnSig}`
}

function camelCase(s: string): string {
  const pascal = pascalCase(s)
  if (!pascal) return s
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function readPackageOption(args: ParsedArgs, space: Space): string {
  const flag = args.flags.package
  if (typeof flag === 'string' && flag.length > 0) return sanitizeGoPackage(flag)
  return sanitizeGoPackage(space.meta.id)
}

function sanitizeGoPackage(id: string): string {
  // Go package names are lowercase ASCII, no dashes. Replace separators
  // with underscores; if the result starts with a digit, prefix with `pkg_`.
  const cleaned = id
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '')
  if (!cleaned) return 'pizza_doc'
  if (/^[0-9]/.test(cleaned)) return `pkg_${cleaned}`
  return cleaned
}

// ==========================================================================
// Operations (config-map + external-deps + ADR index)
// ==========================================================================

/**
 * `pd export operations [--module <id>] [--include-decisions] [--out <file>]`
 *
 * Render a single Markdown document covering the *operational* layer of a
 * space: every module's config-map and external dependencies, plus an
 * index of ADRs (with optional full-text inclusion). This is what a
 * deployer / ops engineer / on-call needs the morning of a rollout, in
 * one page.
 *
 * The format is intentionally org-neutral: it surfaces *what* the system
 * needs (env vars, secrets, outbound deps, decisions touching this
 * module), not *how* a particular org provides it. Provisioning lives
 * in org-specific runbooks, not here.
 */
async function exportOperations(args: ParsedArgs): Promise<number> {
  const { space } = await loadSpaceForCli(resolveSpaceDir(args.positional[0]))
  const opts: OperationsRenderOptions = {
    includeDecisions: args.flags['include-decisions'] === true,
  }
  if (typeof args.flags.module === 'string') opts.moduleFilter = args.flags.module
  const out = renderOperations(space, opts)
  return emit(out, readCodegenOptions(args))
}

interface OperationsRenderOptions {
  moduleFilter?: string
  includeDecisions: boolean
}

export function renderOperations(space: Space, opts: OperationsRenderOptions): string {
  const lines: string[] = []
  const modules = opts.moduleFilter
    ? space.modules.filter((m) => m.id === opts.moduleFilter)
    : space.modules
  if (opts.moduleFilter && modules.length === 0) {
    return `# Operations: ${space.meta.id}\n\n_No module with id '${opts.moduleFilter}'._\n`
  }
  lines.push(`# Operations — ${space.meta.name} (${space.meta.id}@${space.meta.version})`)
  lines.push('')
  lines.push(
    '> Source of truth for what each module needs from the outside world. Generated; do not edit.',
  )
  lines.push('')

  for (const mod of modules) {
    if (mod.configMap.length === 0 && mod.externalDeps.length === 0 && mod.decisions.length === 0) {
      continue
    }
    lines.push(`## ${mod.name} (\`${mod.id}\`) — ${mod.type}`)
    lines.push('')
    if (mod.description) {
      lines.push(mod.description.trim())
      lines.push('')
    }
    if (mod.configMap.length > 0) {
      lines.push('### Configuration')
      lines.push('')
      lines.push('| Key | Type | Lifecycle | Mutability | Consumer | Source of truth | Default |')
      lines.push('|---|---|---|---|---|---|---|')
      const sorted = [...mod.configMap].sort(
        (a, b) => secretsFirst(a, b) || a.key.localeCompare(b.key),
      )
      for (const c of sorted) {
        lines.push(
          `| \`${c.key}\` | ${c.type === 'secret' ? '🔒 secret' : 'config'} | ${c.lifecycle} | ${c.mutability} | ${refToShort(c.consumer.component)} | ${escapeCell(c.sourceOfTruth ?? (c.type === 'secret' ? '⚠ unresolved' : '—'))} | ${escapeCell(c.defaultValue ?? '—')} |`,
        )
      }
      lines.push('')
      // If anything has `related:` cross-pairs, surface them as a small
      // sub-list — easy to miss in a wide table.
      const pairs = sorted.flatMap((c) =>
        c.related.length > 0 ? [{ key: c.key, related: c.related }] : [],
      )
      if (pairs.length > 0) {
        lines.push('**Cross-pairs:**')
        for (const p of pairs) {
          lines.push(`- \`${p.key}\` ↔ ${p.related.map((r) => `\`${r}\``).join(', ')}`)
        }
        lines.push('')
      }
      const defaultSources = sorted.flatMap((c) =>
        c.defaultSources.length > 0 ? [{ key: c.key, sources: c.defaultSources }] : [],
      )
      if (defaultSources.length > 0) {
        lines.push('**Default sources:**')
        for (const entry of defaultSources) {
          lines.push(
            `- \`${entry.key}\`: ${entry.sources.map((s) => `${s.source ?? 'source'} ${s.sourceRef} = \`${s.value}\``).join('; ')}`,
          )
        }
        lines.push('')
      }
    }
    if (mod.externalDeps.length > 0) {
      lines.push('### External dependencies')
      lines.push('')
      // Split by kind: http-api keeps the legacy table, host-* kinds get
      // their own table because the relevant columns differ.
      type ExternalDep = (typeof mod.externalDeps)[number]
      type HttpApiDep = Extract<ExternalDep, { auth: unknown }>
      type HostDep = Extract<ExternalDep, { kind: 'host-binary' | 'host-artifact' | 'apt-package' }>
      const sorted = [...mod.externalDeps].sort((a, b) => a.name.localeCompare(b.name))
      const httpApiDeps = sorted.filter(
        (d): d is HttpApiDep => d.kind === 'http-api' || d.kind === undefined,
      )
      const hostDeps = sorted.filter(
        (d): d is HostDep =>
          d.kind === 'host-binary' || d.kind === 'host-artifact' || d.kind === 'apt-package',
      )
      if (httpApiDeps.length > 0) {
        lines.push(
          '| Name | Direction | Protocol | Endpoint | Auth | Uses key | Check | Failure mode |',
        )
        lines.push('|---|---|---|---|---|---|---|---|')
        for (const d of httpApiDeps) {
          const check = d.preflightCheck
            ? `preflight: ${d.preflightCheck.sourceRef}`
            : d.driftProbe
              ? `drift: ${d.driftProbe.sourceRef}`
              : '—'
          lines.push(
            `| \`${d.name}\` | ${d.direction} | ${d.protocol} | \`${d.endpoint}\` | ${d.auth} | ${d.usesConfigKey ? `\`${d.usesConfigKey}\`` : '—'} | ${escapeCell(check)} | ${escapeCell(d.failureMode ?? '—')} |`,
          )
        }
        lines.push('')
      }
      if (hostDeps.length > 0) {
        lines.push('**Host-installed dependencies:**')
        lines.push('')
        lines.push('| Name | Kind | Install path | Owner | Profiles | Lifecycle | Preflight |')
        lines.push('|---|---|---|---|---|---|---|')
        for (const d of hostDeps) {
          const installPath =
            d.kind === 'host-binary' || d.kind === 'host-artifact' ? d.install_path : '—'
          const profiles = d.required_in_profiles.length ? d.required_in_profiles.join(', ') : '—'
          const preflight = d.preflight ? `\`${d.preflight.command}\`` : '—'
          lines.push(
            `| \`${d.name}\` | ${d.kind} | \`${installPath}\` | ${d.install_owner ?? '—'} | ${profiles} | ${d.lifecycle ?? '—'} | ${escapeCell(preflight)} |`,
          )
        }
        lines.push('')
      }
      const argvContracts = httpApiDeps.filter((d) => d.positionalArgs)
      if (argvContracts.length > 0) {
        lines.push('**Positional argv contracts:**')
        for (const dep of argvContracts) {
          const contract = dep.positionalArgs
          if (!contract) continue
          const label = contract.name ?? dep.name
          const test = contract.contractTest?.sourceRef ?? 'untested'
          lines.push(`- \`${dep.name}\` / \`${label}\` — contract test: ${test}`)
          for (const arg of contract.args) {
            const flags = [
              arg.required ? 'required' : 'optional',
              arg.nonempty ? 'nonempty' : undefined,
              arg.secret ? 'secret' : undefined,
              arg.enumValues ? `enum=${arg.enumValues.join('|')}` : undefined,
              arg.defaultValue !== undefined ? `default=${String(arg.defaultValue)}` : undefined,
            ]
              .filter(Boolean)
              .join(', ')
            lines.push(
              `  - #${arg.position} \`${arg.name}\`: ${arg.type}${flags ? ` (${flags})` : ''}`,
            )
          }
        }
        lines.push('')
      }
    }
    if (mod.decisions.length > 0) {
      lines.push('### Decisions affecting this module')
      lines.push('')
      for (const id of mod.decisions) {
        const adr = space.decisions.find((d) => d.id === id)
        if (!adr) {
          lines.push(`- ${id} _(broken link)_`)
          continue
        }
        lines.push(`- [${adr.id}](./decisions/${adr.id}-...md) — ${adr.title} _(${adr.status})_`)
      }
      lines.push('')
    }
  }

  if (space.decisions.length > 0) {
    lines.push('## Decision log (ADRs)')
    lines.push('')
    lines.push('| ID | Title | Status | Date | Decider |')
    lines.push('|---|---|---|---|---|')
    for (const d of space.decisions) {
      lines.push(
        `| ${d.id} | ${escapeCell(d.title)} | ${d.status} | ${d.date ?? '—'} | ${escapeCell(d.decider ?? '—')} |`,
      )
    }
    lines.push('')
    if (opts.includeDecisions) {
      for (const d of space.decisions) {
        lines.push(`### ${d.id} — ${d.title}`)
        lines.push('')
        if (d.body) lines.push(d.body.trim())
        lines.push('')
      }
    }
  }

  return `${lines.join('\n').trimEnd()}\n`
}

function secretsFirst(a: { type: string }, b: { type: string }): number {
  if (a.type === b.type) return 0
  return a.type === 'secret' ? -1 : 1
}

function refToShort(ref: string): string {
  // Trim `module:foo/component:Bar` → `Bar`, keep raw for module-only.
  const m = ref.match(/component:([A-Za-z0-9_-]+)$/)
  if (m?.[1]) return `\`${m[1]}\``
  return `\`${ref}\``
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

// Silence unused-binding warnings.
void bold
void cyan
void dim
