import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import type { ParsedArgs } from '../util/args.js'
import { bold, cyan, dim, red, yellow } from '../util/colors.js'

/**
 * `pd port-from-legacy <archive-path> [--output port-audit.md]` — scaffold a
 * port-from-legacy audit table for a `legacy-archive/` directory.
 *
 * The audit table is a checklist the architect fills in before any new
 * migration: each legacy artifact is classified KEEP / ADAPT / REPLACE / DROP,
 * mapped to a greenfield owner and home, and pinned to a smoke check.
 *
 * Why this exists (Pizza-Doc Improvements Prompt v1 — A7):
 *   Without an explicit port audit, greenfield rewrites silently drop assets.
 *   The firecracker host-stack rewrite (kernel + golden rootfs + apt packages) is the canonical
 *   example: the spec showed `0 warnings` while production was missing the
 *   actual binary files. A signed-off port-audit.md makes that gap impossible.
 *
 * Output format mirrors the prompt's template exactly so an architect or
 * downstream skill can fill cells without ambiguity.
 */
export function cmdPortFromLegacy(args: ParsedArgs): number {
  const archivePath = args.positional[0]
  if (!archivePath) {
    console.error(red('usage: pd port-from-legacy <archive-path> [--output port-audit.md]'))
    return 2
  }

  let archiveStat: ReturnType<typeof statSync>
  try {
    archiveStat = statSync(archivePath)
  } catch {
    console.error(red(`archive path does not exist: ${archivePath}`))
    return 2
  }
  if (!archiveStat.isDirectory()) {
    console.error(red(`archive path is not a directory: ${archivePath}`))
    return 2
  }

  const outFlag = args.flags.output
  const outputPath = typeof outFlag === 'string' ? outFlag : 'port-audit.md'

  const files = collectFiles(archivePath, archivePath)
  if (files.length === 0) {
    console.error(yellow(`no files found under ${archivePath}`))
    return 1
  }

  const owners = inferOwners(files)
  const markdown = renderAuditMarkdown(archivePath, files, owners)
  writeFileSync(outputPath, markdown)

  console.log(`${bold(cyan('port-audit scaffolded'))}`)
  console.log(`  archive  : ${archivePath}`)
  console.log(`  files    : ${files.length}`)
  console.log(`  inferred : ${owners.size} top-level owners`)
  console.log(`  output   : ${outputPath}`)
  console.log('')
  console.log(dim('next:'))
  console.log(dim('  1. Architect classifies every row as KEEP / ADAPT / REPLACE / DROP'))
  console.log(
    dim('  2. Architect fills greenfield owner + home + smoke check per KEEP/ADAPT/REPLACE row'),
  )
  console.log(dim('  3. Architect signs off; orchestrator gates new migration on completed table'))
  return 0
}

/**
 * Walk a directory recursively and collect every file path, sorted, with
 * paths relative to the archive root.
 */
function collectFiles(root: string, dir: string): string[] {
  const out: string[] = []
  let entries: ReturnType<typeof readdirSync>
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    const fullPath = join(dir, entry.name)
    if (entry.name === '.git' || entry.name === 'node_modules') continue
    if (entry.isDirectory()) {
      out.push(...collectFiles(root, fullPath))
    } else if (entry.isFile()) {
      out.push(relative(root, fullPath))
    }
  }
  return out.sort()
}

/**
 * Group files by their first path segment and return a "best guess" greenfield
 * owner for each top-level group. The guess is just the directory name; the
 * architect overrides per row.
 */
function inferOwners(files: string[]): Map<string, string> {
  const owners = new Map<string, string>()
  for (const file of files) {
    const top = file.split('/')[0] ?? ''
    if (!top) continue
    if (!owners.has(top)) {
      // Heuristic: top-level dir name doubles as the suggested owner.
      // Architect renames per row when wrong.
      owners.set(top, top)
    }
  }
  return owners
}

/**
 * Render the audit markdown. Format mirrors the template from
 * `pizza_doc_improvements_prompt.md` §A7 so reviewers know what to expect.
 */
function renderAuditMarkdown(
  archivePath: string,
  files: string[],
  owners: Map<string, string>,
): string {
  const lines: string[] = []
  lines.push(`# Port-from-legacy audit — ${archivePath}`)
  lines.push('')
  lines.push(`Generated by \`pd port-from-legacy\`. Files discovered: ${files.length}.`)
  lines.push('')
  lines.push(
    '**Workflow.** Each row is a legacy artifact that needs an explicit decision before any new migration starts. ' +
      'Replace `?` cells with KEEP / ADAPT / REPLACE / DROP. For every KEEP/ADAPT/REPLACE row, fill in the greenfield owner, ' +
      'greenfield home (path in the new repo), and a smoke check (script + section that proves it works).',
  )
  lines.push('')
  lines.push(
    '| Legacy artifact | Path | KEEP / ADAPT / REPLACE / DROP | Greenfield owner | Greenfield home | Smoke check |',
  )
  lines.push('|---|---|---|---|---|---|')
  for (const file of files) {
    const top = file.split('/')[0] ?? ''
    const artifactName = file.split('/').pop() ?? file
    const owner = owners.get(top) ?? '?'
    lines.push(`| ${artifactName} | \`${file}\` | ? | ${owner} | ? | ? |`)
  }
  lines.push('')
  lines.push('## Architect sign-off')
  lines.push('')
  lines.push(`- [ ] All ${files.length} items in ${archivePath}/ classified`)
  lines.push('- [ ] All KEEP/ADAPT/REPLACE mapped to owner + home + smoke')
  lines.push('- [ ] All DROP items have explicit reason')
  lines.push('- [ ] Architect: <signature>')
  lines.push('')
  lines.push('## Notes')
  lines.push('')
  lines.push('Inferred top-level owners (override per row if wrong):')
  for (const [top, owner] of [...owners].sort()) {
    lines.push(`- \`${top}/\` → ${owner}`)
  }
  lines.push('')
  return lines.join('\n')
}
