kind: usecase
id: uc
name: uses UsedDto
actor: actor:sys
trigger: cron
steps:
  - from: module:ui/component:Home
    to: module:api/component:Receiver
    via: module:api/model:UsedDto
  - from: module:api/component:Receiver
    to: module:ui/component:Home
