import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { renderGoInterfaces, renderGoTypes, renderTypeScriptTypes } from '../src/commands/export.js'
import { loadSpaceForCli } from '../src/util/load.js'

/**
 * Codegen unit tests. Each test:
 *   1. mkdtemp → write a tiny self-consistent space (one module + a handful
 *      of models / a component with methods), schemas + pragma omitted because
 *      the loader doesn't need them.
 *   2. loadSpaceForCli → real validate pipeline, so we know the spec is
 *      well-formed before generating from it.
 *   3. assert against the generated string with `toMatch` / `toContain`.
 *      Snapshot tests would be brittle to whitespace changes; targeted
 *      regex covers the contract that matters (banner present, optional
 *      fields use `?:` / `*T`, enums become typed strings, etc.).
 */

interface Fixture {
  tmp: string
  spaceDir: string
}

function makeSpace(): Fixture {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pd-codegen-test-'))
  const spaceDir = path.join(tmp, '.pizza-doc')
  fs.mkdirSync(path.join(spaceDir, 'actors'), { recursive: true })
  fs.mkdirSync(path.join(spaceDir, 'modules', 'agent', 'components'), { recursive: true })
  fs.mkdirSync(path.join(spaceDir, 'modules', 'agent', 'models'), { recursive: true })
  fs.mkdirSync(path.join(spaceDir, 'use-cases'), { recursive: true })
  fs.writeFileSync(
    path.join(spaceDir, 'space.yaml'),
    [
      'meta:',
      '  id: codegen-fixture',
      '  name: Codegen Fixture',
      '  description: Tiny test space.',
      '  version: 1.2.3',
      '  pizzaDocVersion: 0.2.0',
    ].join('\n'),
  )
  fs.writeFileSync(
    path.join(spaceDir, 'modules', 'agent', 'module.yaml'),
    'kind: module\nid: agent\nname: Agent\ntype: service\ntechStack: Go\n',
  )
  fs.writeFileSync(
    path.join(spaceDir, 'modules', 'agent', 'models', 'RuntimeId.yaml'),
    [
      'kind: model',
      'id: RuntimeId',
      'name: RuntimeId',
      'modelKind: enum',
      'description: The runtime that executes a session.',
      'values:',
      '  - claude-code',
      '  - opencode',
    ].join('\n'),
  )
  fs.writeFileSync(
    path.join(spaceDir, 'modules', 'agent', 'models', 'StartRequest.yaml'),
    [
      'kind: model',
      'id: StartRequest',
      'name: StartRequest',
      'modelKind: dto',
      'description: Payload to start a run.',
      'fields:',
      '  - name: prompt',
      '    type: string',
      '  - name: runtime',
      '    type: RuntimeId',
      '  - name: env',
      '    type: Map<string, string>',
      '    optional: true',
      '  - name: deadline',
      '    type: timestamp',
      '    optional: true',
    ].join('\n'),
  )
  fs.writeFileSync(
    path.join(spaceDir, 'modules', 'agent', 'models', 'StartResponse.yaml'),
    [
      'kind: model',
      'id: StartResponse',
      'name: StartResponse',
      'modelKind: dto',
      'fields:',
      '  - name: runId',
      '    type: uuid',
      '  - name: events',
      '    type: List<string>',
    ].join('\n'),
  )
  fs.writeFileSync(
    path.join(spaceDir, 'modules', 'agent', 'components', 'Driver.yaml'),
    [
      'kind: component',
      'id: Driver',
      'name: Driver',
      'type: service',
      'description: Orchestrates one run end-to-end.',
      'methods:',
      '  - name: start',
      '    description: Kick off a run.',
      '    params:',
      '      - name: req',
      '        type: StartRequest',
      '    returns: StartResponse',
      '  - name: cancel',
      '    params:',
      '      - name: runId',
      '        type: uuid',
      '    returns: void',
    ].join('\n'),
  )
  return { tmp, spaceDir }
}

let fixture: Fixture

beforeEach(() => {
  fixture = makeSpace()
})

afterEach(() => {
  fs.rmSync(fixture.tmp, { recursive: true, force: true })
})

describe('renderTypeScriptTypes', () => {
  it('emits a banner, a typed enum union, and a Values const', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderTypeScriptTypes(space)
    expect(out).toMatch(/^\/\/ Code generated by pizza-doc\. DO NOT EDIT\./m)
    expect(out).toMatch(/Regenerate with: pd export typescript-types/)
    expect(out).toMatch(/Source: space codegen-fixture@1\.2\.3/)
    expect(out).toMatch(/export type RuntimeId = "claude-code" \| "opencode"/)
    expect(out).toMatch(/export const RuntimeIdValues = \["claude-code", "opencode"\] as const/)
  })

  it('maps spec field types to TypeScript and respects optional', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderTypeScriptTypes(space)
    expect(out).toMatch(/export interface StartRequest \{/)
    expect(out).toMatch(/prompt: string/)
    expect(out).toMatch(/runtime: RuntimeId/)
    expect(out).toMatch(/env\?: Record<string, string>/)
    // timestamp → string (ISO 8601 by convention).
    expect(out).toMatch(/deadline\?: string/)
    expect(out).toMatch(/runId: string/)
    expect(out).toMatch(/events: string\[\]/)
  })

  it('preserves descriptions as JSDoc on interfaces and fields', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderTypeScriptTypes(space)
    expect(out).toMatch(/\/\*\* Payload to start a run\. \*\//)
    expect(out).toMatch(/\/\*\* The runtime that executes a session\. \*\//)
  })
})

describe('renderGoTypes', () => {
  it('emits a banner that go vet recognises and the requested package', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoTypes(space, 'agent')
    expect(out).toMatch(/^\/\/ Code generated by pizza-doc\. DO NOT EDIT\.$/m)
    expect(out).toMatch(/^package agent$/m)
  })

  it('renders enums as typed strings + a const block', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoTypes(space, 'agent')
    expect(out).toMatch(/type RuntimeId string/)
    expect(out).toMatch(/RuntimeIdClaudeCode RuntimeId = "claude-code"/)
    expect(out).toMatch(/RuntimeIdOpencode RuntimeId = "opencode"/)
  })

  it('uses pointer types and omitempty for optional non-slice fields', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoTypes(space, 'agent')
    // env is Map<string, string> with optional=true → map type, omitempty,
    // no pointer wrap (maps have a nil zero value).
    expect(out).toMatch(/Env map\[string\]string `json:"env,omitempty"`/)
    // deadline is timestamp + optional → *time.Time + omitempty.
    expect(out).toMatch(/Deadline \*time\.Time `json:"deadline,omitempty"`/)
    // Required fields don't get a pointer.
    expect(out).toMatch(/Prompt string `json:"prompt"`/)
  })

  it('adds the `time` import only when needed', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoTypes(space, 'agent')
    expect(out).toMatch(/^import "time"$/m)
  })

  it('PascalCases struct field names and preserves the wire name in tags', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoTypes(space, 'agent')
    expect(out).toMatch(/RunId string `json:"runId"`/)
  })
})

describe('renderGoInterfaces', () => {
  it('emits a banner and the requested package', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoInterfaces(space, 'agent')
    expect(out).toMatch(/^\/\/ Code generated by pizza-doc\. DO NOT EDIT\.$/m)
    expect(out).toMatch(/^package agent$/m)
  })

  it('declares one interface per component-with-methods, with PascalCase method names', async () => {
    const { space } = await loadSpaceForCli(fixture.spaceDir)
    const out = renderGoInterfaces(space, 'agent')
    expect(out).toMatch(/type Driver interface \{/)
    // void returns become a single error.
    expect(out).toMatch(/Cancel\(runId string\) error/)
    // Non-void returns get (T, error).
    expect(out).toMatch(/Start\(req StartRequest\) \(StartResponse, error\)/)
  })
})
